version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=4
      - NODE_MAX_INSTANCES=4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9001:5900"
  firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=4
      - NODE_MAX_INSTANCES=4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9002:5900"