version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node
      - image: selenium/standalone-chrome:3.11.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: create docker network
          command: docker network create grid
      - run:
          name: install selenium-hub
          command: docker run -d --rm -p 4444:4444 --net grid --name selenium-hub selenium/hub
      - run:
          name: install selenium-node
          command: docker run -d --rm --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports
workflows:
  maven_test:
    jobs:
      - build
  version: 2