version: 2
jobs:
  setup_project:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'
      - run:
          name: Preparing tests
          command: mvn verify --settings 'pom.xml' -DskipTests=true
  test_chrome:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: selenium/standalone-chrome
    steps:
      - run:
          name: Run Tests on Chrome
          command: mvn surefire:test -DskipTests=false -Dbrowser=chrome
  test_firefox:
    docker:
        - image: circleci/openjdk:8-jdk-browsers
        - image: selenium/standalone-firefox
    steps:
      - run:
          name: Run Tests on Firefox
          command: mvn surefire:test -DskipTests=false -Dbrowser=firefox
  report:
    steps:
      docker:
        - image: circleci/openjdk:8-jdk-browsers
      steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports
workflows:
  maven_test:
    jobs:
      - setup_project
      - test_chrome
      - test_firefox
      - report
  version: 2